# BrapiClient
"""
client.py — BrapiClient: generated entity entry points.

This file is generated by the Thymeleaf Python template (BrapiClient.txt).
DO NOT EDIT MANUALLY — changes will be overwritten on the next generation run.

Hand-written infrastructure lives in _base_client.py (BaseBrapiClient).
"""
from __future__ import annotations

from ._base_client import BaseBrapiClient

from .entities.allelematrix import AlleleMatrixQuery
from .entities.breedingmethod import BreedingMethodQuery
from .entities.call import CallQuery
from .entities.callset import CallSetQuery
from .entities.crop import CropQuery
from .entities.cross import CrossQuery
from .entities.crossingproject import CrossingProjectQuery
from .entities.cultivar import CultivarQuery
from .entities.cultivarattribute import CultivarAttributeQuery
from .entities.cultivarattributevalue import CultivarAttributeValueQuery
from .entities.event import EventQuery
from .entities.genomemap import GenomeMapQuery
from .entities.germplasm import GermplasmQuery
from .entities.germplasmattribute import GermplasmAttributeQuery
from .entities.germplasmattributevalue import GermplasmAttributeValueQuery
from .entities.image import ImageQuery
from .entities.inventorylot import InventoryLotQuery
from .entities.inventorylotattribute import InventoryLotAttributeQuery
from .entities.inventorylotattributevalue import InventoryLotAttributeValueQuery
from .entities.inventorylotset import InventoryLotSetQuery
from .entities.list import ListQuery
from .entities.locale import LocaleQuery
from .entities.localeattribute import LocaleAttributeQuery
from .entities.localeattributevalue import LocaleAttributeValueQuery
from .entities.location import LocationQuery
from .entities.markerposition import MarkerPositionQuery
from .entities.method import MethodQuery
from .entities.observation import ObservationQuery
from .entities.observationunit import ObservationUnitQuery
from .entities.observationunitattribute import ObservationUnitAttributeQuery
from .entities.observationunitattributevalue import ObservationUnitAttributeValueQuery
from .entities.observationvariable import ObservationVariableQuery
from .entities.ontology import OntologyQuery
from .entities.pedigreenode import PedigreeNodeQuery
from .entities.person import PersonQuery
from .entities.plannedcross import PlannedCrossQuery
from .entities.plate import PlateQuery
from .entities.program import ProgramQuery
from .entities.reference import ReferenceQuery
from .entities.referenceset import ReferenceSetQuery
from .entities.sample import SampleQuery
from .entities.scale import ScaleQuery
from .entities.season import SeasonQuery
from .entities.study import StudyQuery
from .entities.trait import TraitQuery
from .entities.trial import TrialQuery
from .entities.variant import VariantQuery
from .entities.variantset import VariantSetQuery
from .entities.variety import VarietyQuery
from .entities.varietyattribute import VarietyAttributeQuery
from .entities.varietyattributevalue import VarietyAttributeValueQuery
from .entities.varietystage import VarietyStageQuery



class BrapiClient(BaseBrapiClient):
    """
    Single entry-point for all BrAPI v2 queries.

    Inherits connection setup, authentication, and transport lifecycle from
    :class:`BaseBrapiClient`.  Each property below returns a fresh query object
    bound to the shared HTTP transport.

    Example::

        from brapi import BrapiClient

        client = BrapiClient(
            base_url="https://brapi.example.org",
            token_endpoint="https://brapi.example.org/token",
            client_id="svc-account",
            client_secret="...",
        )


        df = client.alleleMatrix.fetch().to_df()

        df = client.breedingMethod.fetch().to_df()

        df = client.call.fetch().to_df()
    """

    # ------------------------------------------------------------------
    # Entity entry points
    # ------------------------------------------------------------------


    @property
    def alleleMatrix(self) -> AlleleMatrixQuery:
        """
        Entry point for AlleleMatrix queries.

        Returns a fresh :class:`AlleleMatrixQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.alleleMatrix.fetch().to_df()
        """
        return AlleleMatrixQuery(http=self._http)

    @property
    def breedingMethod(self) -> BreedingMethodQuery:
        """
        Entry point for BreedingMethod queries.

        Returns a fresh :class:`BreedingMethodQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.breedingMethod.fetch().to_df()
        """
        return BreedingMethodQuery(http=self._http)

    @property
    def call(self) -> CallQuery:
        """
        Entry point for Call queries.

        Returns a fresh :class:`CallQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.call.fetch().to_df()
        """
        return CallQuery(http=self._http)

    @property
    def callSet(self) -> CallSetQuery:
        """
        Entry point for CallSet queries.

        Returns a fresh :class:`CallSetQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.callSet.fetch().to_df()
        """
        return CallSetQuery(http=self._http)

    @property
    def crop(self) -> CropQuery:
        """
        Entry point for Crop queries.

        Returns a fresh :class:`CropQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.crop.fetch().to_df()
        """
        return CropQuery(http=self._http)

    @property
    def cross(self) -> CrossQuery:
        """
        Entry point for Cross queries.

        Returns a fresh :class:`CrossQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.cross.fetch().to_df()
        """
        return CrossQuery(http=self._http)

    @property
    def crossingProject(self) -> CrossingProjectQuery:
        """
        Entry point for CrossingProject queries.

        Returns a fresh :class:`CrossingProjectQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.crossingProject.fetch().to_df()
        """
        return CrossingProjectQuery(http=self._http)

    @property
    def cultivar(self) -> CultivarQuery:
        """
        Entry point for Cultivar queries.

        Returns a fresh :class:`CultivarQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.cultivar.fetch().to_df()
        """
        return CultivarQuery(http=self._http)

    @property
    def cultivarAttribute(self) -> CultivarAttributeQuery:
        """
        Entry point for CultivarAttribute queries.

        Returns a fresh :class:`CultivarAttributeQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.cultivarAttribute.fetch().to_df()
        """
        return CultivarAttributeQuery(http=self._http)

    @property
    def cultivarAttributeValue(self) -> CultivarAttributeValueQuery:
        """
        Entry point for CultivarAttributeValue queries.

        Returns a fresh :class:`CultivarAttributeValueQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.cultivarAttributeValue.fetch().to_df()
        """
        return CultivarAttributeValueQuery(http=self._http)

    @property
    def event(self) -> EventQuery:
        """
        Entry point for Event queries.

        Returns a fresh :class:`EventQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.event.fetch().to_df()
        """
        return EventQuery(http=self._http)

    @property
    def genomeMap(self) -> GenomeMapQuery:
        """
        Entry point for GenomeMap queries.

        Returns a fresh :class:`GenomeMapQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.genomeMap.fetch().to_df()
        """
        return GenomeMapQuery(http=self._http)

    @property
    def germplasm(self) -> GermplasmQuery:
        """
        Entry point for Germplasm queries.

        Returns a fresh :class:`GermplasmQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.germplasm.fetch().to_df()
        """
        return GermplasmQuery(http=self._http)

    @property
    def germplasmAttribute(self) -> GermplasmAttributeQuery:
        """
        Entry point for GermplasmAttribute queries.

        Returns a fresh :class:`GermplasmAttributeQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.germplasmAttribute.fetch().to_df()
        """
        return GermplasmAttributeQuery(http=self._http)

    @property
    def germplasmAttributeValue(self) -> GermplasmAttributeValueQuery:
        """
        Entry point for GermplasmAttributeValue queries.

        Returns a fresh :class:`GermplasmAttributeValueQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.germplasmAttributeValue.fetch().to_df()
        """
        return GermplasmAttributeValueQuery(http=self._http)

    @property
    def image(self) -> ImageQuery:
        """
        Entry point for Image queries.

        Returns a fresh :class:`ImageQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.image.fetch().to_df()
        """
        return ImageQuery(http=self._http)

    @property
    def inventoryLot(self) -> InventoryLotQuery:
        """
        Entry point for InventoryLot queries.

        Returns a fresh :class:`InventoryLotQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.inventoryLot.fetch().to_df()
        """
        return InventoryLotQuery(http=self._http)

    @property
    def inventoryLotAttribute(self) -> InventoryLotAttributeQuery:
        """
        Entry point for InventoryLotAttribute queries.

        Returns a fresh :class:`InventoryLotAttributeQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.inventoryLotAttribute.fetch().to_df()
        """
        return InventoryLotAttributeQuery(http=self._http)

    @property
    def inventoryLotAttributeValue(self) -> InventoryLotAttributeValueQuery:
        """
        Entry point for InventoryLotAttributeValue queries.

        Returns a fresh :class:`InventoryLotAttributeValueQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.inventoryLotAttributeValue.fetch().to_df()
        """
        return InventoryLotAttributeValueQuery(http=self._http)

    @property
    def inventoryLotSet(self) -> InventoryLotSetQuery:
        """
        Entry point for InventoryLotSet queries.

        Returns a fresh :class:`InventoryLotSetQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.inventoryLotSet.fetch().to_df()
        """
        return InventoryLotSetQuery(http=self._http)

    @property
    def list(self) -> ListQuery:
        """
        Entry point for List queries.

        Returns a fresh :class:`ListQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.list.fetch().to_df()
        """
        return ListQuery(http=self._http)

    @property
    def locale(self) -> LocaleQuery:
        """
        Entry point for Locale queries.

        Returns a fresh :class:`LocaleQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.locale.fetch().to_df()
        """
        return LocaleQuery(http=self._http)

    @property
    def localeAttribute(self) -> LocaleAttributeQuery:
        """
        Entry point for LocaleAttribute queries.

        Returns a fresh :class:`LocaleAttributeQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.localeAttribute.fetch().to_df()
        """
        return LocaleAttributeQuery(http=self._http)

    @property
    def localeAttributeValue(self) -> LocaleAttributeValueQuery:
        """
        Entry point for LocaleAttributeValue queries.

        Returns a fresh :class:`LocaleAttributeValueQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.localeAttributeValue.fetch().to_df()
        """
        return LocaleAttributeValueQuery(http=self._http)

    @property
    def location(self) -> LocationQuery:
        """
        Entry point for Location queries.

        Returns a fresh :class:`LocationQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.location.fetch().to_df()
        """
        return LocationQuery(http=self._http)

    @property
    def markerPosition(self) -> MarkerPositionQuery:
        """
        Entry point for MarkerPosition queries.

        Returns a fresh :class:`MarkerPositionQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.markerPosition.fetch().to_df()
        """
        return MarkerPositionQuery(http=self._http)

    @property
    def method(self) -> MethodQuery:
        """
        Entry point for Method queries.

        Returns a fresh :class:`MethodQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.method.fetch().to_df()
        """
        return MethodQuery(http=self._http)

    @property
    def observation(self) -> ObservationQuery:
        """
        Entry point for Observation queries.

        Returns a fresh :class:`ObservationQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.observation.fetch().to_df()
        """
        return ObservationQuery(http=self._http)

    @property
    def observationUnit(self) -> ObservationUnitQuery:
        """
        Entry point for ObservationUnit queries.

        Returns a fresh :class:`ObservationUnitQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.observationUnit.fetch().to_df()
        """
        return ObservationUnitQuery(http=self._http)

    @property
    def observationUnitAttribute(self) -> ObservationUnitAttributeQuery:
        """
        Entry point for ObservationUnitAttribute queries.

        Returns a fresh :class:`ObservationUnitAttributeQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.observationUnitAttribute.fetch().to_df()
        """
        return ObservationUnitAttributeQuery(http=self._http)

    @property
    def observationUnitAttributeValue(self) -> ObservationUnitAttributeValueQuery:
        """
        Entry point for ObservationUnitAttributeValue queries.

        Returns a fresh :class:`ObservationUnitAttributeValueQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.observationUnitAttributeValue.fetch().to_df()
        """
        return ObservationUnitAttributeValueQuery(http=self._http)

    @property
    def observationVariable(self) -> ObservationVariableQuery:
        """
        Entry point for ObservationVariable queries.

        Returns a fresh :class:`ObservationVariableQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.observationVariable.fetch().to_df()
        """
        return ObservationVariableQuery(http=self._http)

    @property
    def ontology(self) -> OntologyQuery:
        """
        Entry point for Ontology queries.

        Returns a fresh :class:`OntologyQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.ontology.fetch().to_df()
        """
        return OntologyQuery(http=self._http)

    @property
    def pedigreeNode(self) -> PedigreeNodeQuery:
        """
        Entry point for PedigreeNode queries.

        Returns a fresh :class:`PedigreeNodeQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.pedigreeNode.fetch().to_df()
        """
        return PedigreeNodeQuery(http=self._http)

    @property
    def person(self) -> PersonQuery:
        """
        Entry point for Person queries.

        Returns a fresh :class:`PersonQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.person.fetch().to_df()
        """
        return PersonQuery(http=self._http)

    @property
    def plannedCross(self) -> PlannedCrossQuery:
        """
        Entry point for PlannedCross queries.

        Returns a fresh :class:`PlannedCrossQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.plannedCross.fetch().to_df()
        """
        return PlannedCrossQuery(http=self._http)

    @property
    def plate(self) -> PlateQuery:
        """
        Entry point for Plate queries.

        Returns a fresh :class:`PlateQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.plate.fetch().to_df()
        """
        return PlateQuery(http=self._http)

    @property
    def program(self) -> ProgramQuery:
        """
        Entry point for Program queries.

        Returns a fresh :class:`ProgramQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.program.fetch().to_df()
        """
        return ProgramQuery(http=self._http)

    @property
    def reference(self) -> ReferenceQuery:
        """
        Entry point for Reference queries.

        Returns a fresh :class:`ReferenceQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.reference.fetch().to_df()
        """
        return ReferenceQuery(http=self._http)

    @property
    def referenceSet(self) -> ReferenceSetQuery:
        """
        Entry point for ReferenceSet queries.

        Returns a fresh :class:`ReferenceSetQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.referenceSet.fetch().to_df()
        """
        return ReferenceSetQuery(http=self._http)

    @property
    def sample(self) -> SampleQuery:
        """
        Entry point for Sample queries.

        Returns a fresh :class:`SampleQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.sample.fetch().to_df()
        """
        return SampleQuery(http=self._http)

    @property
    def scale(self) -> ScaleQuery:
        """
        Entry point for Scale queries.

        Returns a fresh :class:`ScaleQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.scale.fetch().to_df()
        """
        return ScaleQuery(http=self._http)

    @property
    def season(self) -> SeasonQuery:
        """
        Entry point for Season queries.

        Returns a fresh :class:`SeasonQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.season.fetch().to_df()
        """
        return SeasonQuery(http=self._http)

    @property
    def study(self) -> StudyQuery:
        """
        Entry point for Study queries.

        Returns a fresh :class:`StudyQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.study.fetch().to_df()
        """
        return StudyQuery(http=self._http)

    @property
    def trait(self) -> TraitQuery:
        """
        Entry point for Trait queries.

        Returns a fresh :class:`TraitQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.trait.fetch().to_df()
        """
        return TraitQuery(http=self._http)

    @property
    def trial(self) -> TrialQuery:
        """
        Entry point for Trial queries.

        Returns a fresh :class:`TrialQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.trial.fetch().to_df()
        """
        return TrialQuery(http=self._http)

    @property
    def variant(self) -> VariantQuery:
        """
        Entry point for Variant queries.

        Returns a fresh :class:`VariantQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.variant.fetch().to_df()
        """
        return VariantQuery(http=self._http)

    @property
    def variantSet(self) -> VariantSetQuery:
        """
        Entry point for VariantSet queries.

        Returns a fresh :class:`VariantSetQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.variantSet.fetch().to_df()
        """
        return VariantSetQuery(http=self._http)

    @property
    def variety(self) -> VarietyQuery:
        """
        Entry point for Variety queries.

        Returns a fresh :class:`VarietyQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.variety.fetch().to_df()
        """
        return VarietyQuery(http=self._http)

    @property
    def varietyAttribute(self) -> VarietyAttributeQuery:
        """
        Entry point for VarietyAttribute queries.

        Returns a fresh :class:`VarietyAttributeQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.varietyAttribute.fetch().to_df()
        """
        return VarietyAttributeQuery(http=self._http)

    @property
    def varietyAttributeValue(self) -> VarietyAttributeValueQuery:
        """
        Entry point for VarietyAttributeValue queries.

        Returns a fresh :class:`VarietyAttributeValueQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.varietyAttributeValue.fetch().to_df()
        """
        return VarietyAttributeValueQuery(http=self._http)

    @property
    def varietyStage(self) -> VarietyStageQuery:
        """
        Entry point for VarietyStage queries.

        Returns a fresh :class:`VarietyStageQuery` bound to the shared transport.
        Filter methods are chainable and immutable — each call returns a new
        query object leaving this initial query unmodified.

        Example::

            client.varietyStage.fetch().to_df()
        """
        return VarietyStageQuery(http=self._http)



# Generated by Schema Tools Generator Version: '0.57.0'
